---
- name: Deploy Kubernetes High Availability Cluster
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    control_plane_endpoint: "{{ control_plane_endpoint }}"
    pod_network_cidr: "{{ pod_network_cidr }}"
    service_cidr: "{{ service_cidr }}"

  tasks:
    - name: Include basic system setup tasks
      include_tasks: tasks/01-system-setup.yml

    - name: Include containerd installation tasks
      include_tasks: tasks/02-containerd.yml

    - name: Include Kubernetes installation tasks
      include_tasks: tasks/03-kubernetes.yml

- name: Setup kube-vip on master nodes
  hosts: masters
  become: yes
  tasks:
    - name: Include kube-vip setup tasks
      include_tasks: tasks/09-kube-vip-setup.yml

- name: Create kubeadm init config on first master
  hosts: masters[0]
  become: yes
  tasks:
    - name: Include kubeadm init config tasks
      include_tasks: tasks/10-kubeadm-init-config.yml

- name: Setup HAProxy Load Balancer
  hosts: loadbalancer
  become: yes
  tasks:
    - name: Include HAProxy setup tasks
      include_tasks: tasks/04-haproxy.yml

- name: Initialize first master node
  hosts: masters[0]
  become: yes
  tasks:
    - name: Include cluster initialization tasks
      include_tasks: tasks/05-cluster-init.yml

- name: Install Calico CNI Network Plugin
  hosts: masters[0]
  become: yes
  tasks:
    - name: Include Calico installation tasks
      include_tasks: tasks/11-calico-install.yml

- name: Join additional master nodes
  hosts: masters[1:]
  become: yes
  tasks:
    - name: Include master join tasks
      include_tasks: tasks/06-master-join.yml

- name: Join worker nodes
  hosts: workers
  become: yes
  tasks:
    - name: Include worker join tasks
      include_tasks: tasks/07-worker-join.yml

- name: Configure node labels and final setup
  hosts: masters[0]
  become: yes
  tasks:
    - name: Include node labels setup
      include_tasks: tasks/12-node-labels.yml