---
# 設定台灣時區
- name: Set timezone to Asia/Taipei
  timezone:
    name: Asia/Taipei

# 安裝 chrony 校時服務
- name: Install chrony for time synchronization
  apt:
    name: chrony
    state: present
    update_cache: yes

- name: Configure chrony to use Google NTP
  blockinfile:
    path: /etc/chrony/chrony.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Google NTP"
    block: |
      server time.google.com prefer
    insertafter: "^pool.*"

- name: Comment out default NTP pools
  replace:
    path: /etc/chrony/chrony.conf
    regexp: '^(pool.*ubuntu.*$)'
    replace: '#\1'

- name: Enable and restart chrony
  systemd:
    name: chrony
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Update system packages
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: Update /etc/hosts with cluster nodes
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
  loop:
    - "10.10.7.230 master-01"
    - "10.10.7.231 master-02"
    - "10.10.7.232 master-03"
    - "10.10.7.233 worker-01"
    - "10.10.7.234 worker-02"
    - "10.10.7.220 haproxy-lb"

- name: Disable swap
  shell: swapoff -a
  ignore_errors: yes

- name: Remove swap entries from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '#\1'

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Add kernel modules to load at boot
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: yes
  loop:
    - overlay
    - br_netfilter

- name: Configure network parameters for Kubernetes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  loop:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }