---
- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Backup original HAProxy configuration
  copy:
    src: /etc/haproxy/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg.backup
    remote_src: yes
    backup: yes

- name: Configure HAProxy for Kubernetes API server load balancing
  copy:
    dest: /etc/haproxy/haproxy.cfg
    content: |
      global
          log stdout local0
          chroot /var/lib/haproxy
          stats socket /run/haproxy/admin.sock mode 660 level admin
          stats timeout 30s
          user haproxy
          group haproxy
          daemon

      defaults
          mode http
          log global
          option httplog
          option dontlognull
          option log-health-checks
          option forwardfor
          option http-server-close
          timeout connect 5000
          timeout client 50000
          timeout server 50000

      frontend kubernetes-frontend
          bind *:6443
          mode tcp
          option tcplog
          timeout client 10s
          default_backend kubernetes-backend

      backend kubernetes-backend
          mode tcp
          option tcplog
          option tcp-check
          balance roundrobin
          timeout server 10s
          server master-01 10.10.7.230:6443 check
          server master-02 10.10.7.231:6443 check
          server master-03 10.10.7.232:6443 check
    backup: yes

- name: Restart and enable HAProxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Verify HAProxy is running
  systemd:
    name: haproxy
    state: started