---
- name: Read worker join command from file
  slurp:
    src: /tmp/worker_join_command
  register: worker_join_command_file
  delegate_to: localhost

- name: Set worker join command fact
  set_fact:
    worker_join_command: "{{ worker_join_command_file.content | b64decode | trim }}"

- name: Check if node is already joined to cluster
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join worker node to cluster
  shell: "{{ worker_join_command }}"
  when: not kubelet_conf.stat.exists