---
# 為 worker 節點添加標籤 (僅在第一個 master 節點執行)
- name: Add worker role label to worker nodes
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ item }}"
        labels:
          node-role.kubernetes.io/worker: ""
    kubeconfig: /root/.kube/config
  loop: "{{ groups['workers'] }}"
  when: inventory_hostname == groups['masters'][0]

- name: Create crictl configuration
  copy:
    dest: /etc/crictl.yaml
    content: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
      timeout: 10
    mode: '0644'

- name: Verify cluster nodes
  shell: kubectl get nodes --kubeconfig=/root/.kube/config
  register: cluster_nodes
  when: inventory_hostname == groups['masters'][0]

- name: Display cluster nodes
  debug:
    var: cluster_nodes.stdout_lines
  when: inventory_hostname == groups['masters'][0]