---
- name: Stage 1 - System Setup
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Set Taiwan timezone
      timezone:
        name: Asia/Taipei
        
    - name: Install chrony
      apt:
        name: chrony
        state: present
        update_cache: yes
        
    - name: Enable chrony service
      systemd:
        name: chrony
        enabled: yes
        
    - name: Configure chrony
      lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: '^#?pool.*ubuntu.*'
        line: '#pool 0.ubuntu.pool.ntp.org iburst maxsources 1'
        state: present
        
    - name: Add Google time server
      lineinfile:
        path: /etc/chrony/chrony.conf
        line: 'server time.google.com prefer'
        state: present
        
    - name: Restart chrony
      systemd:
        name: chrony
        state: restarted
        daemon_reload: yes
        
    - name: Disable swap
      command: swapoff -a
      
    - name: Remove swap from fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*\s+swap\s+.*)$'
        replace: '#\1'
        
    - name: Load kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter
        
    - name: Configure kernel modules to load on boot
      copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf
        
    - name: Configure sysctl parameters
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        
    - name: Apply sysctl parameters
      command: sysctl --system
      
    - name: Reboot if needed
      reboot:
        msg: "Reboot initiated by Ansible for system configuration"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: ansible_reboot_required is defined