---
- name: Stage 7 - Join Master Nodes
  hosts: masters:!first_master
  become: yes
  tasks:
    - name: Wait for first master to be ready
      wait_for:
        port: 6443
        host: "10.10.7.236"
        delay: 10
        timeout: 300
        
    - name: Join master nodes
      command: "{{ hostvars['master-01']['master_join_command'] }}"
      register: join_result
      until: join_result.rc == 0
      retries: 3
      delay: 30
      
    - name: Create .kube directory for root
      file:
        path: /root/.kube
        state: directory
        
    - name: Copy admin.conf to root's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        
    - name: Create .kube directory for ansible user
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      when: ansible_user != 'root'
        
    - name: Copy admin.conf to ansible user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        remote_src: yes
      when: ansible_user != 'root'
        
    - name: Verify master node joined
      shell: kubectl get nodes {{ inventory_hostname }}
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: node_status
      until: node_status.rc == 0
      retries: 10
      delay: 30